### ISSUE TITLE
Fails to compile under node 14.20.0 - any tips?

### ISSUE THREAD

**Issue by webhype** [pankyka/sem#1]
```
$ yarn add git+ssh://git@github.com:pankyka/sem.git
yarn add v1.22.19
warning ../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
[3/5] ⠈ fs-ext
[4/5] ⠈ posix-semaphore
error /Users/macuser/test-semaphore-mutex/node_modules/sem: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/macuser/test-semaphore-mutex/node_modules/sem
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.20.0 | darwin | x64
gyp info find Python using Python version 3.9.13 found at "/usr/local/opt/python@3.9/bin/python3.9"
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/macuser/test-semaphore-mutex/node_modules/sem/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/macuser/Library/Caches/node-gyp/14.20.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/macuser/Library/Caches/node-gyp/14.20.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/macuser/test-semaphore-mutex/node_modules/sem',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/sem/src/sem.o
../src/sem.cc:56:46: error: too few arguments to function call, single argument 'context' was not specified
    String::Utf8Value utf8(info[0]->ToString());
                           ~~~~~~~~~~~~~~~~~ ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8.h:2810:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/sem.cc:68:46: error: too few arguments to function call, single argument 'context' was not specified
    String::Utf8Value utf8(info[0]->ToString());
                           ~~~~~~~~~~~~~~~~~ ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8.h:2810:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/sem.cc:104:55: error: too few arguments to function call, single argument 'context' was not specified
        timeout_millisec = (long)info[0]->NumberValue();
                                 ~~~~~~~~~~~~~~~~~~~~ ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8.h:2861:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/sem.cc:154:50: error: too few arguments to function call, single argument 'context' was not specified
        String::Utf8Value utf8(info[0]->ToString());
                               ~~~~~~~~~~~~~~~~~ ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8.h:2810:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/macuser/Library/Caches/node-gyp/14.20.0/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
4 errors generated.
make: *** [Release/obj.target/sem/src/sem.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node@14/14.20.0/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macuser/test-semaphore-mutex/node_modules/sem

```

**Comment by pankyka** [comment]
Hi @webhype,
I don't have a mac or linux machine at the moment, but according to your log and node-gyp's docs I would first check [node-gyp on macos](https://github.com/nodejs/node-gyp#on-macos), If I were you.

**Comment by pankyka** [comment]
Maybe use `npm install --build-from-resource` instead of yarn.

**Comment by webhype** [comment]
Hi there, thanks for your support! Your project seems the most complete mapping of the POSIX sem mechanism to Node, that's why I am really motivated to get it going. Most packages out there force you into a blocking wait for the semaphore to become available, while your package allows to just "test" (with a timeout), to see whether the semaphore is locked or not.

I followed the instructions on the gyp on MacOS page, and essentially got the same error output. `yarn` /  `npm` seem to perform these exact same steps and arrive at the same result.

I know next to nothing about `gyp`, but I found a similar project that *does* compile out of the box: https://github.com/dbousque/posix-semaphore/blob/master/binding.gyp (unfortunately it doesn't serve my purpose because, again, it forces me to wait to acquire the semaphore with no way out).

You see in that `binding.gyp` that they did something special for NodeJS v11 and up. Perhaps that triggers an immediate idea of what could be the issue with your project? (Unfortunately `posix-semaphore` doesn't serve my purpose because, again, it forces me to wait to acquire the semaphore with no way out).

Thanks again!
